# Generated by Django 4.2.4 on 2023-08-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0002_remove_customuser_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
