# Generated by Django 4.2.5 on 2023-10-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0003_alter_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
