# Generated by Django 4.2.3 on 2023-10-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0005_remove_customuser_address_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='userid',
        ),
    ]
