# Generated by Django 4.2.3 on 2023-10-12 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0011_remove_items_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
