# Generated by Django 4.2.3 on 2023-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0013_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
