# Generated by Django 4.2.3 on 2023-10-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0014_items_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(default='active', max_length=100, null=True),
        ),
    ]
