# Generated by Django 4.2.3 on 2023-10-14 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0015_alter_items_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
