# Generated by Django 4.2.3 on 2023-10-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0016_items_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
