# Generated by Django 4.2.3 on 2023-10-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0017_items_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='media/profile'),
        ),
    ]
