# Generated by Django 4.2.3 on 2023-10-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0018_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('car_number', models.CharField(max_length=20)),
                ('driver_image', models.ImageField(blank=True, null=True, upload_to='driver_images/')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='driver_images/')),
            ],
        ),
    ]
