# Generated by Django 4.2.3 on 2023-10-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0019_driverregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
