# Generated by Django 4.2.3 on 2023-10-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0020_driverregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='vehicle_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
