# Generated by Django 4.2.3 on 2023-10-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0021_driverregistration_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
