# Generated by Django 4.2.3 on 2023-10-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0022_driverregistration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
