# Generated by Django 4.2.3 on 2023-11-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0023_driverregistration_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
        migrations.AddField(
            model_name='items',
            name='images',
            field=models.ManyToManyField(to='uniapp.image'),
        ),
    ]
